Repository arklian/patina, pull requests merged in 2024-06, with the labels that each got.

#57 Kelly: updated title and fonts
  js/src/personal/kelly/Kelly.module.css
  js/src/personal/kelly/Kelly.page.tsx
Labels: -waiting for updates

#45 Jionghao: Added button to switch light/dark modes
  js/package.json
  js/pnpm-lock.yaml
  js/src/personal/jionghao/FooterSocial.module.css
  js/src/personal/jionghao/FooterSocial.tsx
  js/src/personal/jionghao/Jionghao.module.css
  js/src/personal/jionghao/Jionghao.page.tsx
Labels: -shippable

#44 Haoking: Added homepage, image
  js/package.json
  js/pnpm-lock.yaml
  js/src/Router.tsx
  js/src/personal/Haoking/Haoking.page.tsx
  js/src/personal/haoking/Haoking.module.css
  js/src/personal/haoking/Haoking.page.tsx
Labels: -waiting for updates

#35 JsInfra: Create nav links to each personal page
  js/src/Router.tsx
  js/src/Routes.tsx
  js/src/components/Welcome/Welcome.tsx
Labels: -ready for review

#56 Bryan: Created settings menu, light/dark mode, started navbar
  js/src/personal/bryan/Bryan.module.css
  js/src/personal/bryan/Bryan.page.tsx
  js/src/personal/bryan/LightDark.tsx
  js/src/personal/bryan/Settings.tsx
  js/src/personal/bryan/TimeDisplay.tsx
Labels: -waiting for updates, -shippable

#59 Tony: Created page layout, added image and social buttons
  js/src/personal/tony/Tony.module.css
  js/src/personal/tony/Tony.page.tsx
Labels: -ready for review

#62 Bryan: Changed font/TimeDisplay; Added Status
  js/src/personal/bryan/Bryan.module.css
  js/src/personal/bryan/Bryan.page.tsx
  js/src/personal/bryan/LightDark.tsx
  js/src/personal/bryan/Settings.tsx
  js/src/personal/bryan/Status.tsx
  js/src/personal/bryan/TimeDisplay.tsx
Labels: -waiting for updates, -shippable

#65 [Kelly] Updated website components
  js/src/personal/kelly/Kelly.module.css
  js/src/personal/kelly/Kelly.page.tsx
Labels: -ready for review

#63 Haoking: Embed spotify, timer component, refactor
  js/src/personal/haoking/Haoking.module.css
  js/src/personal/haoking/Haoking.page.tsx
  js/src/personal/haoking/LeftAboutMe.tsx
  js/src/personal/haoking/RightAboutMe.tsx
  js/src/personal/haoking/Time.tsx
  js/src/personal/haoking/theme.ts
Labels: -shippable

#66 Bryan: Added NavBar component
  js/src/personal/bryan/Bryan.module.css
  js/src/personal/bryan/Bryan.page.tsx
  js/src/personal/bryan/NavBar.tsx
  js/src/personal/bryan/Settings.tsx
  js/src/personal/bryan/Status.tsx
  js/src/personal/bryan/TimeDisplay.tsx
  js/src/personal/bryan/theme.ts
Labels: -ready for review

#68 Bryan: Added in base social media footer
  js/src/personal/bryan/Bryan.page.tsx
  js/src/personal/bryan/NavBar.tsx
  js/src/personal/bryan/Settings.tsx
  js/src/personal/bryan/Socials.tsx
Labels: -ready for review

#70 Amanda: Changed styling and included icons
  js/src/personal/amanda/Amanda.module.css
  js/src/personal/amanda/Contact.tsx
  js/src/personal/amanda/Data.json
  js/src/personal/amanda/Main.page.tsx
  js/src/personal/amanda/Navbar.tsx
  js/src/personal/amanda/Section.tsx
  js/src/personal/amanda/theme.ts
Labels: -ready for review

#53 Riyuan/personal web
  js/package.json
  js/pnpm-lock.yaml
  js/src/personal/riyuan/Riyuan.module.css
  js/src/personal/riyuan/Riyuan.page.tsx
  js/src/personal/riyuan/assets/images/pfp.jpg
  js/src/personal/riyuan/components/about/about.tsx
  js/src/personal/riyuan/components/home/home.tsx
  js/src/personal/riyuan/components/navigation/Navigation.module.css
  js/src/personal/riyuan/components/navigation/Navigation.tsx
Labels: -waiting for updates, -shippable

#69 Bryan: Added routing system to allow for subpages
  js/src/Routes.tsx
  js/src/personal/bryan/AboutMe.page.tsx
  js/src/personal/bryan/Bryan.page.tsx
  js/src/personal/bryan/Fun.page.tsx
  js/src/personal/bryan/Main.page.tsx
  js/src/personal/bryan/Projects.page.tsx
Labels: -ready for review, -shippable

#75 Kazi: Creation of Navbar
  js/src/personal/kazi/Kazi.module.css
  js/src/personal/kazi/Kazi.page.tsx
  js/src/personal/kazi/components/DarkModeToggle/DarkModeToggle.module.css
  js/src/personal/kazi/components/DarkModeToggle/DarkModeToggle.tsx
  js/src/personal/kazi/components/Navbar/Navbar.module.css
  js/src/personal/kazi/components/Navbar/Navbar.tsx
Labels: -waiting for updates, -shippable

#74 Riyuan: Structured the Website layout
  js/src/personal/riyuan/Riyuan.module.css
  js/src/personal/riyuan/Riyuan.page.tsx
  js/src/personal/riyuan/components/about/About.tsx
  js/src/personal/riyuan/components/about/about.tsx
  js/src/personal/riyuan/components/contact/Contact.tsx
  js/src/personal/riyuan/components/footer/Footer.tsx
  js/src/personal/riyuan/components/footer/FooterCentered.module.css
  js/src/personal/riyuan/components/home/Home.tsx
  js/src/personal/riyuan/components/home/home.tsx
  js/src/personal/riyuan/components/navigation/Navigation.module.css
  js/src/personal/riyuan/components/navigation/Navigation.tsx
  js/src/personal/riyuan/components/project/Project.tsx
  js/src/personal/riyuan/components/timeline/Timeline.tsx
Labels: -waiting for updates, -shippable
