Repository arklian/patina, pull requests merged in 2024-07, with the labels that each got.

#79 Manny: Added a home/menu hub
  js/src/personal/manny/Manny.page.tsx
  js/src/personal/manny/assets/PicOfManny.jpg
  js/src/personal/manny/components/ClickableImage.module.css
  js/src/personal/manny/components/ClickableImage.tsx
  js/src/personal/manny/components/FooterSocial.module.css
  js/src/personal/manny/components/FooterSocial.tsx
Labels: -waiting for updates, -shippable

#71 Haoking: Functioning navbar, fade-in animation
  js/src/personal/haoking/Haoking.module.css
  js/src/personal/haoking/Haoking.page.tsx
  js/src/personal/haoking/aboutme/AboutMe.tsx
  js/src/personal/haoking/aboutme/LeftAboutMe.tsx
  js/src/personal/haoking/aboutme/RightAboutMe.tsx
  js/src/personal/haoking/components/NavLink.tsx
  js/src/personal/haoking/components/Navbar.tsx
  js/src/personal/haoking/components/Time.tsx
  js/src/personal/haoking/misc/MiscPage.tsx
  js/src/personal/haoking/pages.ts
  js/src/personal/haoking/projects/LeftProjects.tsx
  js/src/personal/haoking/projects/ProjectsPage.tsx
  js/src/personal/haoking/projects/RightProjects.tsx
Labels: -shippable

#84 Kazi: Fixed nits and global css changes
  js/src/personal/kazi/Kazi.module.css
  js/src/personal/kazi/Kazi.page.tsx
  js/src/personal/kazi/components/Hero/Hero.module.css
  js/src/personal/kazi/components/Hero/Hero.tsx
  js/src/personal/kazi/components/Navbar/Navbar.module.css
  js/src/personal/kazi/components/Navbar/Navbar.tsx
Labels: -ready for review

#87 Bryan: Reworked fun page/moved clock/footer
  js/src/personal/bryan/AboutMe/AboutMe.module.css
  js/src/personal/bryan/AboutMe/AboutMePictures.tsx
  js/src/personal/bryan/Bryan.module.css
  js/src/personal/bryan/Bryan.page.tsx
  js/src/personal/bryan/Frame/TimeDisplay.tsx
  js/src/personal/bryan/Fun/Fun.module.css
  js/src/personal/bryan/Fun/Fun.page.tsx
  js/src/personal/bryan/Projects/Projects.module.css
  js/src/personal/bryan/Projects/Projects.page.tsx
Labels: -ready for review

#90 Tony: Added project section with links
  js/src/personal/tony/Tony.module.css
  js/src/personal/tony/Tony.page.tsx
Labels: -shippable

#89 Jionghao: Add Experience section
  js/src/personal/jionghao/Jionghao.page.tsx
  js/src/personal/jionghao/components/About.module.css
  js/src/personal/jionghao/components/Experience.module.css
  js/src/personal/jionghao/components/Experience.tsx
  js/src/personal/jionghao/components/Header.module.css
  js/src/personal/jionghao/components/Hero.module.css
  js/src/personal/jionghao/components/Work.module.css
  js/src/personal/jionghao/components/Work.tsx
Labels: -shippable

#95 Kazi: Finished Hero Section
  js/src/personal/kazi/Kazi.page.tsx
  js/src/personal/kazi/assets/bitmoji_hero.png
  js/src/personal/kazi/assets/bitmoji_hero_circle.png
  js/src/personal/kazi/components/Hero/Hero.module.css
  js/src/personal/kazi/components/Hero/Hero.tsx
  js/src/personal/kazi/components/darkmodetoggle/DarkModeToggle.module.css
  js/src/personal/kazi/components/darkmodetoggle/DarkModeToggle.tsx
  js/src/personal/kazi/components/hero/Hero.module.css
  js/src/personal/kazi/components/hero/Hero.tsx
  js/src/personal/kazi/components/navbar/Navbar.module.css
  js/src/personal/kazi/components/navbar/Navbar.tsx
Labels: -ready for review

#93 Riyuan: Fixed style on Container
  js/src/personal/riyuan/Riyuan.module.css
  js/src/personal/riyuan/components/about/About.module.css
  js/src/personal/riyuan/components/about/About.tsx
  js/src/personal/riyuan/components/contact/Contact.tsx
  js/src/personal/riyuan/components/experience/Experience.module.css
  js/src/personal/riyuan/components/experience/Experience.tsx
  js/src/personal/riyuan/components/experience/TabGroup.tsx
  js/src/personal/riyuan/components/experience/TabPanel.tsx
  js/src/personal/riyuan/components/experience/TimelineComponent.tsx
  js/src/personal/riyuan/components/experience/TimelineItem.tsx
  js/src/personal/riyuan/components/experience/data.ts
  js/src/personal/riyuan/components/home/Home.module.css
  js/src/personal/riyuan/components/home/Home.tsx
  js/src/personal/riyuan/components/project/Project.tsx
Labels: -shippable

#97 Amanda: Replaced info, added light/dark mode, and updated layout
  js/src/personal/amanda/Amanda.module.css
  js/src/personal/amanda/Amanda.page.tsx
  js/src/personal/amanda/Contact.tsx
  js/src/personal/amanda/Data.json
  js/src/personal/amanda/Landing.page.tsx
  js/src/personal/amanda/LightDarkButton.tsx
  js/src/personal/amanda/Main.page.tsx
  js/src/personal/amanda/Navbar.tsx
  js/src/personal/amanda/ProjectContent.tsx
  js/src/personal/amanda/SectionContent.tsx
  js/src/personal/amanda/Sidebar.tsx
  js/src/personal/amanda/Types.tsx
Labels: -shippable
